services:
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    ports:
      - 5000:5000
    environment:
      SECRET_KEY: "GDtfDCFYjD"
      SQLALCHEMY_DATABASE_URI: "postgresql+psycopg2://postgres:admin@db:5432/cloud_db"
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    command: bash -c "python3 -m flask run -h 0.0.0.0 -p 5000"
  db:
    build: ./data
    environment:
      POSTGRES_DB: cloud_db
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
    volumes:
      - cloud-db-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  cloud-db-data:
    external: true